name: Build & Deploy to Azure Container Instance

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops_project:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops_project:latest

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Instance
        run: |
          az container create \
            --resource-group devops_project-rg \
            --name devops-container \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/devops_project:latest \
            --cpu 1 \
            --memory 1 \
            --ports 8081 \
            --ip-address Public \
            --location northeurope \
            --restart-policy Always
